import type { Publication } from '@/types/content';

const legacyCompleted =
  'https://bkschoolofresearch.blogspot.com/p/completed.html';
const base = {
  status: 'published' as const,
  createdAt: '2018-01-01T00:00:00.000Z',
  updatedAt: '2026-08-30T00:00:00.000Z',
  doi: null as string | null,
  originalLegacyUrl: legacyCompleted,
};

/** All items transcribed from the legacy Completed page — no invented DOIs */
export const publications: Publication[] = [
  // —— Journal articles ——
  {
    ...base,
    id: 'pub-meo-unemployment-governance-poverty-2020',
    slug: 'impact-of-unemployment-and-governance-on-poverty-in-pakistan',
    publishedAt: '2020-01-01T00:00:00.000Z',
    title:
      'Impact of Unemployment and Governance on Poverty in Pakistan: a Fresh Insight from Non-linear ARDL Co-integration Approach',
    type: 'journal',
    authors: [
      'M. S. Meo',
      'B. Kumar',
      'S. Chughtai',
      'V. J. Khan',
      'M. K. B. Dost',
      'Q. A. Nisar',
    ],
    year: 2020,
    venue: 'Global Business Review',
    pages: '1-18',
    citation:
      'Meo, M. S., Kumar, B., Chughtai, S., Khan, V. J., Dost, M. K. B. and Nisar, Q. A. (2020). Impact of Unemployment and Governance on Poverty in Pakistan: a Fresh Insight from Non-linear ARDL Co-integration Approach. Global Business Review, 1-18.',
    abstract: 'Non-linear ARDL co-integration analysis of unemployment, governance, and poverty in Pakistan.',
    areaIds: ['area-poverty', 'area-public-policy', 'area-business-economics'],
    projectId: 'project-unemployment-governance-poverty-pakistan',
  },
  {
    ...base,
    id: 'pub-islam-kumar-social-network-loneliness-2019',
    slug: 'social-network-social-media-use-loneliness-academic-performance',
    publishedAt: '2019-01-01T00:00:00.000Z',
    title:
      'The Relationship between Social Network, Social Media Use, Loneliness and Academic Performance: A Study among University Students in Bangladesh',
    type: 'journal',
    authors: ['M. A. Islam', 'B. Kumar'],
    year: 2019,
    venue: 'World of Media Journal of Russian Media and Journalism Studies',
    volume: '2019',
    issue: '4',
    pages: '25-47',
    citation:
      'Islam, M. A. and Kumar, B. (2019). The Relationship between Social Network, Social Media Use, Loneliness and Academic Performance: A Study among University Students in Bangladesh. World of Media Journal of Russian Media and Journalism Studies, 2019(4): 25-47.',
    coverImageUrl: '/media/prototype/bksr-knowledge-archive.jpg',
    abstract: 'Examined relationships among social networks, social media use, loneliness, and academic performance for Bangladeshi university students.',
    areaIds: ['area-wellbeing', 'area-education'],
    projectId: 'project-social-network-loneliness-academic-performance',
  },
  {
    ...base,
    id: 'pub-kumar-climate-perception-2019',
    slug: 'perception-and-knowledge-on-climate-change-university-students',
    publishedAt: '2019-01-01T00:00:00.000Z',
    title:
      'Perception and Knowledge on Climate Change: A Case Study on University Students in Bangladesh',
    type: 'journal',
    authors: ['B. Kumar', 'A. I. Asad', 'B. Chandraaroy', 'P. Banik'],
    year: 2019,
    venue: 'Journal of Atmospheric Science Research',
    volume: '2',
    issue: '3',
    pages: '17-22',
    citation:
      'Kumar, B., Asad, A. I., Chandraaroy, B. and Banik, P. (2019). Perception and Knowledge on Climate Change: A Case Study on University Students in Bangladesh. Journal of Atmospheric Science Research, 2(3): 17-22.',
    coverImageUrl: '/media/prototype/bksr-pub-cover-climate.jpg',
    abstract: 'Case study of climate change perception and knowledge among university students in Bangladesh.',
    areaIds: ['area-climate-environment', 'area-education'],
    projectId: 'project-climate-perception-university-students',
  },
  {
    ...base,
    id: 'pub-kumar-remittances-poverty-alleviation-2019',
    slug: 'impact-of-international-remittances-on-poverty-alleviation-bangladesh',
    publishedAt: '2019-01-01T00:00:00.000Z',
    title:
      'The Impact of International Remittances on Poverty Alleviation in Bangladesh',
    type: 'journal',
    authors: ['B. Kumar'],
    year: 2019,
    venue: 'Remittances Review',
    volume: '4',
    issue: '1',
    pages: '67-86',
    citation:
      'Kumar, B. (2019). The Impact of International Remittances on Poverty Alleviation in Bangladesh. Remittances Review, 4(1): 67-86.',
    coverImageUrl: '/media/prototype/bksr-pub-cover-remittances.jpg',
    abstract: 'Analyzed the impact of international remittances on poverty alleviation in Bangladesh.',
    areaIds: ['area-poverty', 'area-business-economics', 'area-social-development'],
    projectId: 'project-remittances-poverty-alleviation',
  },
  {
    ...base,
    id: 'pub-kumar-remittances-poverty-welfare-cumilla-2019',
    slug: 'remittances-poverty-and-welfare-cumilla-bangladesh',
    publishedAt: '2019-01-01T00:00:00.000Z',
    title: 'Remittances, Poverty and Welfare: Evidence from Cumilla, Bangladesh',
    type: 'journal',
    authors: ['B. Kumar'],
    year: 2019,
    venue: 'American Journal of Data Mining and Knowledge Discovery',
    volume: '4',
    issue: '1',
    pages: '46-52',
    citation:
      'Kumar, B. (2019). Remittances, Poverty and Welfare: Evidence from Cumilla, Bangladesh. American Journal of Data Mining and Knowledge Discovery, 4(1): 46-52.',
    abstract: 'Local evidence on remittances, poverty, and welfare from Cumilla, Bangladesh.',
    areaIds: ['area-poverty', 'area-social-development'],
    projectId: 'project-remittances-poverty-welfare-cumilla',
  },
  {
    ...base,
    id: 'pub-kumar-remittances-education-health-2019',
    slug: 'impact-of-international-remittances-education-and-health-bangladesh',
    publishedAt: '2019-01-01T00:00:00.000Z',
    title:
      'The Impact of International Remittances Education and Health in Bangladesh',
    type: 'journal',
    authors: ['B. Kumar'],
    year: 2019,
    venue: 'International Journal of Science and Qualitative Analysis',
    volume: '5',
    issue: '1',
    pages: '6-14',
    citation:
      'Kumar, B. (2019). The Impact of International Remittances Education and Health in Bangladesh. International Journal of Science and Qualitative Analysis, 5(1): 6-14.',
    abstract: 'Studied remittance impacts on education and health outcomes in Bangladesh.',
    areaIds: ['area-education', 'area-health', 'area-business-economics'],
    projectId: 'project-remittances-education-health',
  },
  {
    ...base,
    id: 'pub-kumar-facebook-loneliness-2019',
    slug: 'social-network-facebook-use-and-loneliness-bangladesh',
    publishedAt: '2019-01-01T00:00:00.000Z',
    title:
      'Social Network, Facebook Use and Loneliness: A Comparative Analysis Between Public and Private University Students in Bangladesh',
    type: 'journal',
    authors: ['B. Kumar', 'P. Banik', 'M. A. Islam'],
    year: 2019,
    venue: 'International Journal of Psychological and Brain Science',
    volume: '4',
    issue: '2',
    pages: '20-28',
    citation:
      'Kumar, B., Banik, P. and Islam, M. A. (2019). Social Network, Facebook Use and Loneliness: A Comparative Analysis Between Public and Private University Students in Bangladesh. International Journal of Psychological and Brain Science, 4(2): 20-28.',
    abstract: 'Comparative analysis of Facebook use and loneliness across public and private university students in Bangladesh.',
    areaIds: ['area-wellbeing', 'area-education'],
    projectId: 'project-facebook-use-loneliness',
  },
  {
    ...base,
    id: 'pub-banik-kumar-information-literacy-2019',
    slug: 'impact-of-information-literacy-skill-academic-performance',
    publishedAt: '2019-01-01T00:00:00.000Z',
    title:
      "Impact of Information Literacy Skill on Students' Academic Performance in Bangladesh",
    type: 'journal',
    authors: ['P. Banik', 'B. Kumar'],
    year: 2019,
    venue: 'International Journal of European Studies',
    volume: '3',
    issue: '1',
    pages: '27-33',
    citation:
      "Banik, P. and Kumar, B. (2019). Impact of Information Literacy Skill on Students' Academic Performance in Bangladesh. International Journal of European Studies, 3(1): 27-33.",
    abstract: 'Assessed how information literacy skills relate to students\' academic performance.',
    areaIds: ['area-education'],
    projectId: 'project-information-literacy-academic-performance',
  },
  {
    ...base,
    id: 'pub-das-kumar-military-1971-2019',
    slug: 'indian-military-involvement-1971-east-pakistan',
    publishedAt: '2019-01-01T00:00:00.000Z',
    title:
      'Indian Military Involvement in the 1971 Crisis of East-Pakistan: A Justification of Level of Analysis',
    type: 'journal',
    authors: ['S. Das', 'B. Kumar'],
    year: 2019,
    venue: 'American Journal of Theoretical and Applied Business',
    volume: '5',
    issue: '4',
    pages: '84-89',
    citation:
      'Das, S. and Kumar, B. (2019). Indian Military Involvement in the 1971 Crisis of East-Pakistan: A Justification of Level of Analysis. American Journal of Theoretical and Applied Business, 5(4): 84-89.',
    abstract: 'Level-of-analysis justification of Indian military involvement in the 1971 East-Pakistan crisis.',
    areaIds: ['area-public-policy'],
    projectId: 'project-military-involvement-1971',
  },
  {
    ...base,
    id: 'pub-kumar-utilization-remittances-2018',
    slug: 'utilization-of-international-remittances-bangladesh',
    publishedAt: '2018-01-01T00:00:00.000Z',
    title: 'Utilization of International Remittances in Bangladesh',
    type: 'journal',
    authors: ['B. Kumar', 'M. E. Hossain', 'M. A. G. Osmani'],
    year: 2018,
    venue: 'Remittances Review',
    volume: '3',
    issue: '1',
    pages: '5-18',
    citation:
      'Kumar, B., Hossain, M. E. and Osmani, M. A. G. (2018). Utilization of International Remittances in Bangladesh. Remittances Review, 3(1): 5-18.',
    abstract: 'Examined how international remittances are utilized in Bangladesh.',
    areaIds: ['area-business-economics', 'area-social-development'],
    projectId: 'project-utilization-international-remittances',
  },
  {
    ...base,
    id: 'pub-khan-arch-mexico-2018',
    slug: 'financial-forecasting-arch-family-mexico',
    publishedAt: '2018-01-01T00:00:00.000Z',
    title:
      'Financial Forecasting by Autoregressive Conditional Heteroscedasticity (ARCH) Family: A Case of Mexico',
    type: 'journal',
    authors: ['V. J. Khan', 'A. Qadeer', 'B. Kumar'],
    year: 2018,
    venue: 'Journal of Public Policy and Administration',
    volume: '2',
    issue: '3',
    pages: '32-39',
    citation:
      'Khan, V. J., Qadeer, A. and Kumar B. (2018). Financial Forecasting by Autoregressive Conditional Heteroscedasticity (ARCH) Family: A Case of Mexico. Journal of Public Policy and Administration, 2(3): 32-39.',
    abstract: 'Applied ARCH-family models to financial forecasting for Mexico.',
    areaIds: ['area-business-economics', 'area-public-policy'],
    projectId: 'project-financial-forecasting-arch-mexico',
  },
  {
    ...base,
    id: 'pub-fani-bank-performance-pakistan-2018',
    slug: 'impact-of-internal-and-external-factors-on-bank-performance-pakistan',
    publishedAt: '2018-01-01T00:00:00.000Z',
    title: 'Impact of Internal and External Factors on Bank Performance in Pakistan',
    type: 'journal',
    authors: ['K. A. Fani', 'V. J. Khan', 'B. Kumar', 'B. K. Pk'],
    year: 2018,
    venue: 'International and Public Affairs',
    volume: '2',
    issue: '4',
    pages: '66-77',
    citation:
      'Fani, K. A., Khan, V. J., Kumar, B. and Pk, B. K. (2018). Impact of Internal and External Factors on Bank Performance in Pakistan. International and Public Affairs, 2(4): 66-77.',
    abstract: 'Analyzed internal and external determinants of bank performance in Pakistan.',
    areaIds: ['area-business-economics'],
    projectId: 'project-bank-performance-pakistan',
  },

  // —— Book chapter ——
  {
    ...base,
    id: 'pub-islam-kumar-nexus-social-network-igi-2019',
    slug: 'nexus-between-social-network-social-media-use-and-loneliness',
    publishedAt: '2019-01-01T00:00:00.000Z',
    title:
      'Nexus Between Social Network, Social Media Use and Loneliness: A Case Study of University Students, Bangladesh',
    type: 'book-chapter',
    authors: ['M. A. Islam', 'B. Kumar'],
    year: 2019,
    venue: 'Innovative Management and Business Practices in Asia',
    publisher: 'IGI Global: USA',
    citation:
      'Islam, M. A. and Kumar, B. (2019). Nexus Between Social Network, Social Media Use and Loneliness: A Case Study of University Students, Bangladesh. Innovative Management and Business Practices in Asia. IGI Global: USA.',
    abstract: 'Examined relationships among social networks, social media use, loneliness, and academic performance for Bangladeshi university students.',
    areaIds: ['area-wellbeing', 'area-education'],
    projectId: 'project-social-network-loneliness-academic-performance',
  },

  // —— Conference papers ——
  {
    ...base,
    id: 'pub-kumar-seminar-climate-icpad-2020',
    slug: 'impact-of-seminar-on-students-perception-climate-change-icpad-2020',
    publishedAt: '2020-02-05T00:00:00.000Z',
    title:
      "Impact of Seminar on Students' Perception about Climate Change: A Case Study of Rabindra University, Bangladesh",
    type: 'conference',
    authors: ['B. Kumar', 'B. Chandraaroy'],
    year: 2020,
    venue:
      '7th International Conference on Public Administration and Development (ICPAD) Social Science Research in Bangladesh, Dhaka, Bangladesh',
    citation:
      "Kumar, B. and Chandraaroy, B. (05-08 February, 2020). Impact of Seminar on Students' Perception about Climate Change: A Case Study of Rabindra University, Bangladesh. 7th International Conference on Public Administration and Development (ICPAD) Social Science Research in Bangladesh, Dhaka, Bangladesh.",
    areaIds: ['area-climate-environment', 'area-education'],
  },
  {
    ...base,
    id: 'pub-kumar-climate-perception-conference-2019',
    slug: 'perception-knowledge-climate-change-fourth-annual-conference-2019',
    publishedAt: '2019-11-02T00:00:00.000Z',
    title:
      'Perception and Knowledge on Climate Change: A Case Study on University Students in Bangladesh',
    type: 'conference',
    authors: ['B. Kumar', 'A. I. Asad', 'B. Chandraaroy', 'P. Banik'],
    year: 2019,
    venue:
      'Fourth Annual Conference on Social Science Research in Bangladesh, Dhaka, Bangladesh',
    citation:
      'Kumar, B., Asad, A. I., Chandraaroy, B. and Banik, P. (02 November, 2019). Perception and Knowledge on Climate Change: A Case Study on University Students in Bangladesh. Fourth Annual Conference on Social Science Research in Bangladesh, Dhaka, Bangladesh.',
    abstract: 'Case study of climate change perception and knowledge among university students in Bangladesh.',
    areaIds: ['area-climate-environment'],
    projectId: 'project-climate-perception-university-students',
  },
  {
    ...base,
    id: 'pub-kumar-climate-varendra-conference-2019',
    slug: 'students-perception-knowledge-climate-change-varendra-university',
    publishedAt: '2019-01-01T00:00:00.000Z',
    title:
      "Students' Perception and Knowledge on Climate Change: A Case Study of Varendra University, Bangladesh",
    type: 'conference',
    authors: ['B. Kumar'],
    year: 2019,
    venue:
      "International Conference on Culture, Peace and Education from the Perspective of People's History, University of Rajshahi, Bangladesh",
    citation:
      "Kumar, B. (2019). Students' Perception and Knowledge on Climate Change: A Case Study of Varendra University, Bangladesh. International Conference on Culture, Peace and Education from the Perspective of People's History. University of Rajshahi, Bangladesh.",
    areaIds: ['area-climate-environment', 'area-education'],
  },
  {
    ...base,
    id: 'pub-hossain-academic-performance-icmr-2018',
    slug: 'socioeconomic-institutional-correlates-academic-performance-icmr-2018',
    publishedAt: '2018-11-29T00:00:00.000Z',
    title:
      "Socioeconomic and Intuitional Correlates of Students' Academic of Performance at the University Level of Bangladesh",
    type: 'conference',
    authors: ['M. E. Hossain', 'B. Kumar', 'M. K. Islam'],
    year: 2018,
    venue:
      '9th International Conference on Management Research (ICMR-2018), Lahore, Pakistan',
    citation:
      "Hossain, M. E., Kumar, B. and Islam, M. K. (29-30 November, 2018). Socioeconomic and Intuitional Correlates of Students' Academic of Performance at the University Level of Bangladesh. 9th International Conference on Management Research (ICMR-2018), Lahore, Pakistan.",
    areaIds: ['area-education'],
  },
  {
    ...base,
    id: 'pub-kumar-remittances-human-development-2018',
    slug: 'do-international-remittances-cause-human-development-bangladesh',
    publishedAt: '2018-09-20T00:00:00.000Z',
    title:
      'Do International Remittances Cause Human Development? Examining Bangladesh',
    type: 'conference',
    authors: ['B. Kumar'],
    year: 2018,
    venue: '5th International Conference on Social Sciences 2018, Sri-Lanka',
    citation:
      'Kumar, B. (20-21 September, 2018). Do International Remittances Cause Human Development? Examining Bangladesh. 5th International Conference on Social Sciences 2018, Sri-Lanka.',
    areaIds: ['area-social-development', 'area-business-economics'],
  },
  {
    ...base,
    id: 'pub-kumar-remittances-reduce-poverty-2018',
    slug: 'does-international-remittances-reduce-poverty-bangladesh',
    publishedAt: '2018-09-08T00:00:00.000Z',
    title: 'Does International Remittances Reduce Poverty in Bangladesh?',
    type: 'conference',
    authors: ['B. Kumar', 'M. E. Hossain', 'M. K. Islam'],
    year: 2018,
    venue: '12th International Conference, Bhopal, India',
    citation:
      'Kumar, B., Hossain, M. E. and Islam, M. K. (8-9 September, 2018). Does International Remittances Reduce Poverty in Bangladesh? 12th International Conference, Bhopal, India.',
    areaIds: ['area-poverty'],
  },
  {
    ...base,
    id: 'pub-kumar-broiler-farming-2018',
    slug: 'profitability-and-constraints-of-broiler-farming-bangladesh',
    publishedAt: '2018-08-16T00:00:00.000Z',
    title: 'Profitability and Constraints of Broiler Farming in Bangladesh',
    type: 'conference',
    authors: ['B. Kumar', 'M. E. Hossain', 'M. K. Islam'],
    year: 2018,
    venue:
      'The 5th International Conference on Agriculture 2018 (AGARICI 2018), Colombo, Sri-Lanka',
    citation:
      'Kumar, B., Hossain, M. E. and Islam, M. K. (16 August, 2018). Profitability and Constraints of Broiler Farming in Bangladesh. The 5th International Conference on Agriculture 2018 (AGARICI 2018), Colombo, Sri-Lanka.',
    areaIds: ['area-business-economics'],
  },

  // —— Newspaper / opinion ——
  {
    ...base,
    id: 'pub-kumar-varendra-university-asian-age-2019',
    slug: 'varendra-university-seven-years-enlightening-north-bengal-youths',
    publishedAt: '2019-03-17T00:00:00.000Z',
    title:
      'Varendra University: Seven years of enlightening the North Bengal youths',
    type: 'opinion',
    authors: ['B. Kumar'],
    year: 2019,
    venue: 'The Daily Asian Age',
    volume: '5',
    issue: '266',
    pages: '20',
    citation:
      'Kumar, B. (17 March, 2019). Varendra University: Seven years of enlightening the North Bengal youths. The Daily Asian Age, 5 (266): 20.',
    areaIds: ['area-education'],
  },
  {
    ...base,
    id: 'pub-kumar-probashi-aay-alokito-vor-2018',
    slug: 'probashi-aay-unnoyner-ekti-karyokori-hatiyar',
    publishedAt: '2018-12-02T00:00:00.000Z',
    title: 'Probashi Aay: Unnoyner Ekti Karyokori Hatiyar',
    type: 'opinion',
    authors: ['B. Kumar'],
    year: 2018,
    venue: 'Daily Alokito Vor',
    language: 'bn',
    citation:
      'Kumar, B. (02 December, 2018). Probashi Aay: Unnoyner Ekti Karyokori Hatiyar. Daily Alokito Vor. At Open Blog Page.',
    abstract: 'প্রবাসী আয়: উন্নয়নের একটি কার্যকরী হাতিয়ার বিজন কুমার বাংলাদেশের অর্থনৈতিক নির্ধারকগুলোর ধারাবাহিক অগ্রগতি বিশ্বের ব্যাপক নজর কেড়েছে এবং অব্যাহতভাবে কেড়ে যাচ্ছে । ১৯৭১ সালে স্বাধীনতা অর্জনের সময়ও যেদেশ অতিরিক্ত জনসংখ্যার চাপ, ক্ষুধা ও দারিদ্র্যে ভারাক্রান্ত ছিল; ভরপুর ছিল প্রাকৃত',
    areaIds: ['area-business-economics', 'area-social-development'],
  },
  {
    ...base,
    id: 'pub-kumar-factors-remittance-inflows-2018',
    slug: 'factors-influencing-remittance-inflows-into-bangladesh',
    publishedAt: '2018-11-14T00:00:00.000Z',
    title: 'Factors influencing remittance inflows into Bangladesh',
    type: 'opinion',
    authors: ['B. Kumar'],
    year: 2018,
    venue: 'The Daily Asian Age',
    volume: '5',
    issue: '146',
    pages: '20',
    citation:
      'Kumar, B. (14 November, 2018). Factors influencing remittance inflows into Bangladesh. The Daily Asian Age, 5 (146): 20.',
    areaIds: ['area-business-economics'],
  },
  {
    ...base,
    id: 'pub-kumar-nordhaus-romer-nobel-2018',
    slug: 'why-nordhaus-and-romer-won-nobel-prize-in-economics',
    publishedAt: '2018-10-25T00:00:00.000Z',
    title: 'Why Nordhaus and Romer won Nobel Prize in economics',
    type: 'opinion',
    authors: ['B. Kumar'],
    year: 2018,
    venue: 'The Daily Asian Age',
    volume: '5',
    issue: '126',
    pages: '6',
    citation:
      'Kumar, B. (25 October, 2018). “Why Nordhaus and Romer won Nobel Prize in economics.” The Daily Asian Age, 5 (126): 6.',
    areaIds: ['area-business-economics'],
  },
  {
    ...base,
    id: 'pub-kumar-international-remittances-development-2018',
    slug: 'international-remittances-one-step-ahead-towards-development',
    publishedAt: '2018-10-25T00:00:00.000Z',
    title: 'International Remittances-one step ahead towards development',
    type: 'opinion',
    authors: ['B. Kumar'],
    year: 2018,
    venue: 'The Daily Asian Age',
    volume: '5',
    issue: '126',
    pages: '20',
    citation:
      'Kumar, B. (25 October, 2018). “International Remittances-one step ahead towards development” The Daily Asian Age, 5 (126): 20.',
    areaIds: ['area-business-economics', 'area-social-development'],
  },
  {
    ...base,
    id: 'pub-kumar-nobel-2017-asian-age',
    slug: 'the-story-behind-2017-nobel-prize-in-economics-asian-age',
    publishedAt: '2017-11-12T00:00:00.000Z',
    title: 'The Story behind 2017 Nobel Prize in Economics',
    type: 'opinion',
    authors: ['B. Kumar'],
    year: 2017,
    venue: 'The Daily Asian Age',
    volume: '4',
    issue: '146',
    pages: '20',
    citation:
      'Kumar, B. (12 November, 2017). “The Story behind 2017 Nobel Prize in Economics.” The Daily Asian Age, 4(146): 20.',
    abstract: 'The Story behind 2017 Nobel Prize in Economics Bezon Kumar A few days ago the Nobel Committee declared the name of winners of the world\'s most prestigious prize, Nobel Prize. No doubt, the prize is awarded to those persons and institutions who contribute to the development of',
    areaIds: ['area-behavioral-economics', 'area-business-economics'],
  },
  {
    ...base,
    id: 'pub-kumar-bangabandhu-7-march-asian-age-2017',
    slug: 'bangabandhus-7th-march-speech-part-of-world-heritage-asian-age',
    publishedAt: '2017-11-06T00:00:00.000Z',
    title: "Bangabandhu's 7th March speech: A part of world heritage",
    type: 'opinion',
    authors: ['B. Kumar'],
    year: 2017,
    venue: 'The Daily Asian Age',
    volume: '4',
    issue: '140',
    pages: '20',
    citation:
      'Kumar, B. (06 November, 2017). “Bangabandhu’s 7th March speech: A part of world heritage.” The Daily Asian Age, 4(140): 20.',
    abstract: 'Bangabandhu\'s 7th March Speech: A Part of World Heritage Bezon Kumar No doubt everybody knows that the historical 7th March speech is now a recognized world heritage. A special organization of United Nations, UNESCO- United Nations Educational, Scientific, and Cultural Organizati',
    areaIds: ['area-public-policy'],
  },
  {
    ...base,
    id: 'pub-kumar-climate-bangladesh-asian-age-2017',
    slug: 'climate-change-in-bangladesh-causes-effects-suggestions-asian-age',
    publishedAt: '2017-10-23T00:00:00.000Z',
    title: 'Climate change in Bangladesh: Causes, effects and suggestions',
    type: 'opinion',
    authors: ['B. Kumar'],
    year: 2017,
    venue: 'The Daily Asian Age',
    volume: '4',
    issue: '126',
    pages: '20',
    citation:
      'Kumar, B. (23 October, 2017). “Climate change in Bangladesh: Causes, effects and suggestions.” The Daily Asian Age, 4(126): 20.',
    abstract: 'Climate Change in Bangladesh: Causes, Effects and Suggestions Bezon Kumar Climate change is now one of the biggest problems across the globe as its impacts on human beings and the environment is very terrible and prolonged. Almost all countries of the world are directly or indire',
    areaIds: ['area-climate-environment'],
  },
  {
    ...base,
    id: 'pub-kumar-remittance-mechanism-asian-age-2017',
    slug: 'remittance-an-effective-mechanism-for-development-asian-age',
    publishedAt: '2017-08-23T00:00:00.000Z',
    title: 'Remittance: an effective mechanism for development',
    type: 'opinion',
    authors: ['B. Kumar'],
    year: 2017,
    venue: 'The Daily Asian Age',
    volume: '4',
    issue: '69',
    pages: '20',
    citation:
      'Kumar, B. (23 August, 2017). “Remittance: an effective mechanism for development.” The Daily Asian Age, 4(69): 20.',
    abstract: 'Remittance: an Effective Mechanism for Development Bezon Kumar The successive improvement in economic indicators of Bangladesh has drawn deep attention to world leaders and policymakers. When Bangladesh achieved her independence in 1971, the country was fully burdened with th',
    areaIds: ['area-business-economics', 'area-social-development'],
  },
];
