/**
 * Legacy BKSR (Blogger) → new content model classification map.
 *
 * Source inventory:
 * - src/content/imported/legacy-posts.json (24 posts)
 * - src/content/imported/legacy-pages.json (20 pages)
 *
 * Run: npm run migrate
 * Writes: docs/content-migration-report.md
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

const posts = JSON.parse(
  fs.readFileSync(path.join(root, 'src/content/imported/legacy-posts.json'), 'utf8'),
);
const pages = JSON.parse(
  fs.readFileSync(path.join(root, 'src/content/imported/legacy-pages.json'), 'utf8'),
);

/** Classification rules used for seed generation */
const POST_CLASSIFICATION = {
  events: [
    'covid-19-pandemic-and-child-protection',
    'impact-of-covid-19-on-youth-mental',
    'gender-and-development-fundamentals',
    'globalization-and-youths-in-south-asia',
    'spss-for-beginners',
  ],
  notices: [
    'job-vacancy',
    'bk-school-of-research-is-looking-for',
    'vacancy',
    'vacancy-announcement',
    'blog-post_10',
  ],
  news: [
    'education-and-its-strategy',
    'why-indias-northeast-region-assams',
    'environmental-impact-and-sustainability',
    'core-contribution-of-richard-thaler',
    'the-story-behind-2017-nobel-prize-in_2',
    'bangabandhus-7th-march-speech-part-of',
    'climate-change-in-bangladesh-causes',
    'remittance-effective-mechanism-for',
    // title-matched Bengali / literary posts (slugs collide as blog-post*)
  ],
  newsByTitle: [
    'আমার বাবা আমার গর্ব',
    'সেরা তিনজন লেখক নির্বাচিত',
    'মাকে নিয়ে লিখি',
    '২৬ মার্চ, ১৯৭১',
    'প্রবাসী আয়: উন্নয়নের একটি কার্যকরী হাতিয়ার',
    'গবেষণা: টেকসই উন্নয়নের মূল হাতিয়ার',
  ],
};

const PAGE_CLASSIFICATION = {
  siteAbout: ['about-us'],
  researchOngoing: ['on-going'],
  researchCompleted: ['completed'],
  peopleDirector: ['people'],
  knowledgeHub: [
    'stata',
    'spss',
    'ms-excel',
    'stata_23',
    'stata_21',
    'eviews',
    'spss_23',
  ],
  archiveEmpty: [
    'blog-page',
    'editorial-board',
    'about-saptasudha',
    'staff',
    'research',
    'research-team',
    'fellow',
    'research-assistants',
  ],
  galleryComingSoon: ['galary'],
};

function textLen(item) {
  return (item.fullContentText || '').trim().length;
}

const emptyPages = pages.filter((p) => textLen(p) === 0);
const nearEmptyPages = pages.filter((p) => textLen(p) > 0 && textLen(p) < 50);
const classifiedPostSlugs = new Set([
  ...POST_CLASSIFICATION.events,
  ...POST_CLASSIFICATION.notices,
  ...POST_CLASSIFICATION.news,
]);

const unclassifiedPosts = posts.filter((p) => {
  if (classifiedPostSlugs.has(p.slug)) return false;
  if (POST_CLASSIFICATION.newsByTitle.includes(p.title.trim())) return false;
  return true;
});

const duplicateSlugPosts = (() => {
  const map = new Map();
  for (const p of posts) {
    map.set(p.slug, (map.get(p.slug) || 0) + 1);
  }
  return [...map.entries()].filter(([, n]) => n > 1);
})();

const report = `# BKSR Content Migration Report

Generated by \`scripts/migrate-legacy.mjs\` on ${new Date().toISOString()}.

## Inventory

| Source | Count |
|--------|------:|
| Legacy posts (\`legacy-posts.json\`) | ${posts.length} |
| Legacy pages (\`legacy-pages.json\`) | ${pages.length} |

### Post categories observed (Blogger labels)

${[...new Set(posts.flatMap((p) => p.categories || []))]
  .sort()
  .map((c) => `- ${c}`)
  .join('\n')}

## Classification mapping (posts → new model)

| Legacy signal | New collection | Rule |
|---------------|----------------|------|
| Notice + Slide webinars with event date | \`events\` (past) | Webinar registration posts |
| Job / vacancy circulars | \`notices\` (\`vacancy\`) | Hiring content |
| Writing-contest result notices | \`notices\` / \`news\` | Contest logistics → notices; winners → news |
| Education / climate / economics articles | \`news\` | Editorial / educational posts |
| Newspaper-style opinion pieces already on Completed page | \`publications\` (\`opinion\`) | Prefer citation list over re-import |
| Bengali literary posts (poems, father essay, Mother’s Day contest) | \`news\` or \`activities\` (innovation) | Not research projects |
| Template / widget noise | skipped | None isolated beyond empty pages |

### Events (${POST_CLASSIFICATION.events.length})

${POST_CLASSIFICATION.events.map((s) => `- \`${s}\``).join('\n')}

### Notices (${POST_CLASSIFICATION.notices.length})

${POST_CLASSIFICATION.notices.map((s) => `- \`${s}\``).join('\n')}

### News (slug-based ${POST_CLASSIFICATION.news.length} + title-based ${POST_CLASSIFICATION.newsByTitle.length})

Slug-based:
${POST_CLASSIFICATION.news.map((s) => `- \`${s}\``).join('\n')}

Title-based (needed because several posts share slug \`blog-post\`):
${POST_CLASSIFICATION.newsByTitle.map((t) => `- ${t}`).join('\n')}

## Classification mapping (pages → new model)

| Legacy page | New destination |
|-------------|-----------------|
| \`about-us\` | Site settings mission/vision + \`pages\` Who We Are / What We Do |
| \`people\` | \`people\` — Bezon Kumar only (Executive Director) |
| \`completed\` | \`publications\` + completed \`researchProjects\` |
| \`on-going\` | Ongoing thematic \`researchProjects\` + related \`researchAreas\` |
| Stata / SPSS / Excel / EViews pages | \`resources\` (Knowledge Hub) |
| \`about-saptasudha\`, \`editorial-board\` | \`resources\` archive note (empty source) |
| \`galary\` | \`galleryAlbums\` coming-soon placeholder |
| Empty people/team pages | Skipped — do not invent people |

### Empty pages (skipped / no invented content) — ${emptyPages.length}

${emptyPages.map((p) => `- \`${p.slug}\` — ${p.title.trim()} (${p.originalUrl})`).join('\n')}

### Near-empty pages — ${nearEmptyPages.length}

${nearEmptyPages
  .map((p) => `- \`${p.slug}\` — “${(p.fullContentText || '').trim()}” (${textLen(p)} chars)`)
  .join('\n')}

## Duplicate / colliding items

### Duplicate post slugs

${
  duplicateSlugPosts.length
    ? duplicateSlugPosts
        .map(([slug, n]) => {
          const titles = posts
            .filter((p) => p.slug === slug)
            .map((p) => p.title.trim());
          return `- \`${slug}\` × ${n}: ${titles.map((t) => `“${t}”`).join('; ')}`;
        })
        .join('\n')
    : '- None'
}

Seed data resolves collisions with stable unique slugs (e.g. \`amar-baba-amar-gorbo\`, \`gobeshona-sustainable-development\`).

### Opinion / news overlap

Several newspaper opinions on the Completed page also appear (or closely mirror) blog posts:

- Remittance: an Effective Mechanism for Development
- Climate Change in Bangladesh
- Bangabandhu's 7th March Speech
- The Story behind 2017 Nobel Prize in Economics
- Probashi Aay (Bengali)

**Resolution:** Keep authoritative citation entries in \`publications\` (\`opinion\`); keep blog text in \`news\` where a full post body exists. Do not invent DOIs (none present on legacy).

## Seed content counts (target shape)

See \`src/content/seed/\`. Expected approximate counts after migration:

- People: 1 (Bezon Kumar only)
- Research areas: 13
- Research projects: 12 completed + 12 ongoing themes
- Publications: 12 journal + 1 book chapter + 7 conference + 9 opinion
- Events: 5 past webinars
- Notices: 5
- News: 14
- Activities: 4 types
- Resources: 8 (7 software + Saptasudha)
- Gallery albums: 1 coming-soon (0 images)
- Media: featured images from import (no invented photos)

## Unresolved / follow-up

1. **Social URLs** — Facebook page, YouTube channel, and LinkedIn company URLs recovered from webinar post bodies into site settings; Twitter/Instagram remain empty.
2. **Contact details** — address/phone/emails provided for the new site (not fully present in imported JSON); confirm before production.
3. **Scholar count conflict** — About (~30) vs 2023 vacancy (350+ / 22 countries). Homepage marks 350+ as \`verified: false\`; founded 2015, 20+ publications, 22 countries, Joy Bangla Youth Award 2022 as \`verified: true\` from vacancy notice / about.
4. **Empty team pages** — Fellows, Research Associates, Assistants, Our Team remain empty arrays / draft governance notes until real profiles exist.
5. **Ongoing project titles** — Legacy listed theme counts only; individual ongoing project titles were not published.
6. **Saptasudha archive** — initiative noted; detailed archive empty on legacy.
7. **Unclassified posts after rules** — ${unclassifiedPosts.length}
${
  unclassifiedPosts.length
    ? unclassifiedPosts.map((p) => `   - ${p.title.trim()} (\`${p.slug}\`)`).join('\n')
    : '   - None'
}

## Skipped template noise

Blogger chrome (Follow us links, “Click to Watch” stubs without destinations, empty Archives/Editorial Board shells) was not turned into fake curated content. Knowledge Hub resources retain the limited instructional text that existed.

## Integrity rules applied

- Do not invent people, partners, metrics, or DOIs
- Prefer real legacy titles, citations, and post bodies
- Stable string IDs (e.g. \`person-bezon-kumar\`)
- Gallery remains coming soon
`;

const outPath = path.join(root, 'docs/content-migration-report.md');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, report, 'utf8');

console.log(`Wrote ${outPath}`);
console.log(
  JSON.stringify(
    {
      posts: posts.length,
      pages: pages.length,
      emptyPages: emptyPages.length,
      duplicateSlugs: duplicateSlugPosts.length,
      unclassifiedPosts: unclassifiedPosts.length,
    },
    null,
    2,
  ),
);
